#!/bin/bash
red='\033[1;31m'
white='\033[1;37m'
yel='\033[1;33m'
off='\033[0m'

ip="$(grep -oP '(?<="ip": ")[^"]*' /etc/datadiri.conf)"
isp="$(grep -oP '(?<="org": ")[^"]*' /etc/datadiri.conf)"
city="$(grep -oP '(?<="city": ")[^"]*' /etc/datadiri.conf)"
region="$(grep -oP '(?<="region": ")[^"]*' /etc/datadiri.conf)"
country="$(grep -oP '(?<="country": ")[^"]*' /etc/datadiri.conf)"
loc="$(grep -oP '(?<="loc": ")[^"]*' /etc/datadiri.conf)"
timezone="$(grep -oP '(?<="timezone": ")[^"]*' /etc/datadiri.conf)"
clear
echo " "
echo -e "${white}>>_+=============|${red}Xans Tech Premium Script${white}|==============+_<<"
echo -e "#                                                           #"
echo -e "#                                                           #"
echo -e ">>_+===================|${red}Info Server${white}|=====================+_<<"
echo -e "[${yel}>>${white}]IP/Host               : $ip"
echo -e "[${yel}>>${white}]ISP                   : $isp"
echo -e "[${yel}>>${white}]City                  : $city"
echo -e "[${yel}>>${white}]Region                : $region"
echo -e "[${yel}>>${white}]Country               : $country"
echo -e "[${yel}>>${white}]Location              : $loc"
echo -e "[${yel}>>${white}]Timezone              : $timezone"
echo -e ">>_+===================|${red}Menu V2RAY${white}|======================+_<<"
echo -e "[${yel}>>${white}]addv2ray              : Menambah user V2Ray             #"
echo -e "[${yel}>>${white}]listv2ray             : Melihat daftar User V2Ray       #"
echo -e "[${yel}>>${white}]exp                   : Menghapus User V2ray Yang       #"
echo -e "[${yel}>>${white}]                        sudah expired                   #"
echo -e "[${yel}>>${white}]delv2ray              : Menghapus User V2Ray yang       #"
echo -e "[${yel}>>${white}]                        diinginkan                      #"
echo -e ">>_+==============|${red}Order Premium Script${white}|=================+_<<"
echo -e "#                                                           #"
echo -e "[${yel}>>${white}]               Order Premium Script?                 [<<]"
echo -e "[${yel}>>${white}]                wa.me/6285779533554                  [<<]"
echo -e "[${yel}>>${white}]                   t.me/skuyxans                     [<<]"
echo -e "#                                                           #"
echo -e ">>_+=============|${red}Xans Tech Premium Script${white}|==============+_<<${off}"
